-- proposed-cms-sync-2026.sql
-- Generated by scripts/cms-sync-2026.ts on 2026-06-25T16:32:35.881Z
-- DO NOT EXECUTE BLINDLY. Review before applying.
--
-- Source of truth: CMS CY2026 Landscape + PBP Section_C/D.
-- This file proposes UPDATE statements for every field where the
-- DB disagrees with CMS, plus INSERT shells for plans missing from
-- pm_plans. Plans MISSING_FROM_CMS are listed as comments — most
-- are stale historical plans we should manually de-list, not auto
-- DELETE (some are non-MA products in our DB that don't round-trip
-- through landscape).

-- ── Section 1: UPDATE mismatches in pm_plans ────────────────

BEGIN;

-- S4802-082-000  Wellcare  Wellcare Classic (PDP)
--   premium: CMS=0  DB=null
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='S4802' AND plan_id='082' AND segment_id='000';

-- S4802-145-000  Wellcare  Wellcare Value Script (PDP)
--   premium: CMS=0  DB=null
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='S4802' AND plan_id='145' AND segment_id='000';

-- S5601-020-000  Aetna Medicare  SilverScript Choice (PDP)
--   premium: CMS=100.7  DB=null
UPDATE pm_plans SET monthly_premium = 100.7 WHERE contract_id='S5601' AND plan_id='020' AND segment_id='000';

-- S5617-219-000  HealthSpring  HealthSpring Assurance Rx (PDP)
--   premium: CMS=149.3  DB=null
UPDATE pm_plans SET monthly_premium = 149.3 WHERE contract_id='S5617' AND plan_id='219' AND segment_id='000';

-- S5617-360-000  HealthSpring  HealthSpring Extra Rx (PDP)
--   premium: CMS=71.2  DB=null
UPDATE pm_plans SET monthly_premium = 71.2 WHERE contract_id='S5617' AND plan_id='360' AND segment_id='000';

-- S5884-135-000  Humana  Humana Basic Rx Plan (PDP)
--   premium: CMS=0  DB=null
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='S5884' AND plan_id='135' AND segment_id='000';

-- S5884-156-000  Humana  Humana Premier Rx Plan (PDP)
--   premium: CMS=129.5  DB=null
UPDATE pm_plans SET monthly_premium = 129.5 WHERE contract_id='S5884' AND plan_id='156' AND segment_id='000';

-- S5884-189-000  Humana  Humana Value Rx Plan (PDP)
--   premium: CMS=36.4  DB=null
UPDATE pm_plans SET monthly_premium = 36.4 WHERE contract_id='S5884' AND plan_id='189' AND segment_id='000';

-- S5921-355-000  UnitedHealthcare  AARP Medicare Rx Saver from UHC (PDP)
--   premium: CMS=98  DB=null
UPDATE pm_plans SET monthly_premium = 98 WHERE contract_id='S5921' AND plan_id='355' AND segment_id='000';

-- S5921-392-000  UnitedHealthcare  AARP Medicare Rx Preferred from UHC (PDP)
--   premium: CMS=139.8  DB=null
UPDATE pm_plans SET monthly_premium = 139.8 WHERE contract_id='S5921' AND plan_id='392' AND segment_id='000';

-- H0111-004-000  Wellcare  Wellcare Dual Access Open (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0111' AND plan_id='004' AND segment_id='000';

-- H1112-006-000  Wellcare  Wellcare Dual Access (HMO-POS D-SNP)
--   premium: CMS=0  DB=23.5
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1112' AND plan_id='006' AND segment_id='000';

-- H1112-033-000  Wellcare  Wellcare Dual Liberty (HMO-POS D-SNP)
--   premium: CMS=0  DB=23.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1112' AND plan_id='033' AND segment_id='000';

-- H1112-043-000  Wellcare  Wellcare Assist (HMO-POS)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1112' AND plan_id='043' AND segment_id='000';

-- H1112-046-000  Wellcare  Wellcare Dual Reserve (HMO-POS D-SNP)
--   premium: CMS=0  DB=13.1
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1112' AND plan_id='046' AND segment_id='000';

-- H1889-028-000  UnitedHealthcare  UHC Complete Care Support GA-9 (PPO C-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1889' AND plan_id='028' AND segment_id='000';

-- H2293-001-000  Aetna Medicare  Aetna Medicare Value Care (PPO)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2293' AND plan_id='001' AND segment_id='000';

-- H2293-002-000  Aetna Medicare  Aetna Medicare Dual Extra Care (PPO D-SNP)
--   premium: CMS=0  DB=13.7
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2293' AND plan_id='002' AND segment_id='000';

-- H2293-021-000  Aetna Medicare  Aetna Medicare Dual Extra (PPO D-SNP)
--   premium: CMS=0  DB=11.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2293' AND plan_id='021' AND segment_id='000';

-- H3256-004-002  UnitedHealthcare  UHC Dual Complete GA-S2 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3256' AND plan_id='004' AND segment_id='002';

-- H3256-005-002  UnitedHealthcare  UHC Dual Complete GA-S1 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3256' AND plan_id='005' AND segment_id='002';

-- H3256-006-002  UnitedHealthcare  UHC Dual Complete GA-V1 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3256' AND plan_id='006' AND segment_id='002';

-- H4036-030-000  Anthem Blue Cross and Blue Shield  Anthem Medicare Advantage 2 (PPO)
--   premium: CMS=0  DB=82
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4036' AND plan_id='030' AND segment_id='000';

-- H5141-045-000  Clover Health  Clover Health LiveHealthy Value (PPO)
--   premium: CMS=0  DB=25
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5141' AND plan_id='045' AND segment_id='000';

-- H5216-284-000  Humana  HumanaChoice H5216-284 (PPO)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='284' AND segment_id='000';

-- H5322-049-002  UnitedHealthcare  UHC Dual Complete GA-S3 (HMO-POS D-SNP)
--   premium: CMS=0  DB=11.1
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5322' AND plan_id='049' AND segment_id='002';

-- H5422-013-000  Anthem Blue Cross and Blue Shield  Anthem Extra Help (HMO-POS)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5422' AND plan_id='013' AND segment_id='000';

-- H5453-016-000  Devoted Health  DEVOTED C-SNP CHOICE PLUS 016 GA (PPO C-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5453' AND plan_id='016' AND segment_id='000';

-- H5453-018-000  Devoted Health  DEVOTED C-SNP CHOICE PREMIUM 018 GA (PPO C-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5453' AND plan_id='018' AND segment_id='000';

-- H8093-001-000  Georgia Health Advantage  Georgia Health Advantage (HMO I-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8093' AND plan_id='001' AND segment_id='000';

-- H8093-002-000  Georgia Health Advantage  Georgia Health Advantage Choice (HMO I-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8093' AND plan_id='002' AND segment_id='000';

-- H8390-015-000  CareSource  CareSource Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=17.3
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8390' AND plan_id='015' AND segment_id='000';

-- H8390-017-000  CareSource  CareSource Dual Advantage Plus (HMO D-SNP)
--   premium: CMS=0  DB=14.9
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8390' AND plan_id='017' AND segment_id='000';

-- R0110-020-000  Humana  Humana Full Access R0110-020 (Regional PPO)
--   premium: CMS=0  DB=100
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='R0110' AND plan_id='020' AND segment_id='000';

-- R2604-002-000  UnitedHealthcare  UHC Complete Care Support GS-1A (Regional PPO C-SNP)
--   premium: CMS=0  DB=18.1
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='R2604' AND plan_id='002' AND segment_id='000';

-- H5216-205-000  Humana  HumanaChoice SNP-DE H5216-205 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='205' AND segment_id='000';

-- H5216-206-000  Humana  Humana Dual Select H5216-206 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='206' AND segment_id='000';

-- H5525-049-000  Humana  HumanaChoice H5525-049 (PPO)
--   premium: CMS=0  DB=29
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5525' AND plan_id='049' AND segment_id='000';

-- H8145-069-000  Humana  Humana Gold Choice H8145-069 (PFFS)
--   premium: CMS=0  DB=27
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8145' AND plan_id='069' AND segment_id='000';

-- H3288-042-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=0  DB=43
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='042' AND segment_id='000';

-- H3291-001-000  PruittHealth Premier  PruittHealth Premier (HMO I-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3291' AND plan_id='001' AND segment_id='000';

-- H3291-002-000  PruittHealth Premier  PruittHealth Premier D-SNP (HMO D-SNP)
--   premium: CMS=0  DB=24.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3291' AND plan_id='002' AND segment_id='000';

-- H2293-004-000  Aetna Medicare  Aetna Medicare Dual Care (PPO D-SNP)
--   premium: CMS=0  DB=14.6
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2293' AND plan_id='004' AND segment_id='000';

-- H2293-023-000  Aetna Medicare  Aetna Medicare Value Care (PPO)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2293' AND plan_id='023' AND segment_id='000';

-- H2406-052-000  UnitedHealthcare  UHC Dual Complete GA-D001 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2406' AND plan_id='052' AND segment_id='000';

-- H5216-466-000  Humana  HumanaChoice H5216-466 (PPO)
--   premium: CMS=0  DB=7
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='466' AND segment_id='000';

-- H0439-002-000  HealthSpring  HealthSpring TotalCare (HMO D-SNP)
--   premium: CMS=0  DB=3.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0439' AND plan_id='002' AND segment_id='000';

-- H0439-006-000  HealthSpring  HealthSpring Preferred Plus (HMO)
--   premium: CMS=0  DB=18
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0439' AND plan_id='006' AND segment_id='000';

-- H0439-012-000  HealthSpring  HealthSpring TotalCare Plus (HMO D-SNP)
--   premium: CMS=0  DB=3.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0439' AND plan_id='012' AND segment_id='000';

-- H2293-033-000  Aetna Medicare  Aetna Medicare Value Plus (PPO)
--   premium: CMS=0  DB=20.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2293' AND plan_id='033' AND segment_id='000';

-- H5302-020-000  Aetna Medicare  Aetna Medicare Dual Care (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5302' AND plan_id='020' AND segment_id='000';

-- H0710-033-000  UnitedHealthcare  UHC Nursing Home Plan GA-F001 (PPO I-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0710' AND plan_id='033' AND segment_id='000';

-- H5216-280-001  Humana  HumanaChoice H5216-280 (PPO)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='280' AND segment_id='001';

-- H0439-003-002  HealthSpring  HealthSpring Preferred GA (HMO)
--   premium: CMS=0  DB=30
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0439' AND plan_id='003' AND segment_id='002';

-- H5216-073-000  Humana  HumanaChoice H5216-073 (PPO)
--   premium: CMS=0  DB=45
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='073' AND segment_id='000';

-- H5453-015-000  Devoted Health  DEVOTED C-SNP CHOICE PREMIUM 015 GA (PPO C-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5453' AND plan_id='015' AND segment_id='000';

-- H1608-028-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=0  DB=58
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1608' AND plan_id='028' AND segment_id='000';

-- H5453-017-000  Devoted Health  DEVOTED C-SNP CHOICE PREMIUM 017 GA (PPO C-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5453' AND plan_id='017' AND segment_id='000';

-- H4513-079-000  HealthSpring  HealthSpring TotalCare Plus (HMO D-SNP)
--   premium: CMS=0  DB=8.6
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4513' AND plan_id='079' AND segment_id='000';

-- H4513-080-000  HealthSpring  HealthSpring TotalCare (HMO D-SNP)
--   premium: CMS=0  DB=24.3
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4513' AND plan_id='080' AND segment_id='000';

-- H7917-041-000  BlueCross BlueShield of Tennessee  BlueAdvantage Extra (PPO)
--   premium: CMS=0  DB=27.6
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7917' AND plan_id='041' AND segment_id='000';

-- H1170-002-000  Kaiser Permanente  Kaiser Permanente Senior Advantage Enhanced 1 (HMO)
--   premium: CMS=54  DB=67
UPDATE pm_plans SET monthly_premium = 54 WHERE contract_id='H1170' AND plan_id='002' AND segment_id='000';

-- H1170-016-000  Kaiser Permanente  Kaiser Permanente Senior Advantage Standard (HMO)
--   premium: CMS=12.8  DB=34
UPDATE pm_plans SET monthly_premium = 12.8 WHERE contract_id='H1170' AND plan_id='016' AND segment_id='000';

-- H3256-004-001  UnitedHealthcare  UHC Dual Complete GA-S2 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3256' AND plan_id='004' AND segment_id='001';

-- H3256-005-001  UnitedHealthcare  UHC Dual Complete GA-S1 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3256' AND plan_id='005' AND segment_id='001';

-- H3256-006-001  UnitedHealthcare  UHC Dual Complete GA-V1 (PPO D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3256' AND plan_id='006' AND segment_id='001';

-- H5322-047-001  UnitedHealthcare  AARP Medicare Advantage from UHC GA-5 (HMO-POS)
--   premium: CMS=0  DB=19
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5322' AND plan_id='047' AND segment_id='001';

-- H5322-049-001  UnitedHealthcare  UHC Dual Complete GA-S3 (HMO-POS D-SNP)
--   premium: CMS=0  DB=11.1
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5322' AND plan_id='049' AND segment_id='001';

-- H5521-364-000  Aetna Medicare  Aetna Medicare Value Care (PPO)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5521' AND plan_id='364' AND segment_id='000';

-- H1112-047-000  Wellcare  Wellcare Dual Access (HMO-POS D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1112' AND plan_id='047' AND segment_id='000';

-- H1112-048-000  Wellcare  Wellcare Dual Reserve (HMO-POS D-SNP)
--   premium: CMS=0  DB=25.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1112' AND plan_id='048' AND segment_id='000';

-- H0710-034-000  UnitedHealthcare  UHC Nursing Home Plan NC-F001 (PPO I-SNP)
--   premium: CMS=0  DB=36.2
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 0, moop = 9250 WHERE contract_id='H0710' AND plan_id='034' AND segment_id='000';

-- H1036-167-000  Humana  Humana Gold Plus SNP-DE H1036-167 (HMO D-SNP)
--   premium: CMS=0  DB=14.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1036' AND plan_id='167' AND segment_id='000';

-- H1036-307-000  Humana  Humana Dual Select H1036-307 (HMO D-SNP)
--   premium: CMS=0  DB=13
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1036' AND plan_id='307' AND segment_id='000';

-- H1036-331-000  Humana  Humana Gold Plus SNP-DE H1036-331 (HMO D-SNP)
--   premium: CMS=0  DB=20
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H1036' AND plan_id='331' AND segment_id='000';

-- H1889-005-000  UnitedHealthcare  UHC Dual Complete NC-S001 (PPO D-SNP)
--   premium: CMS=0  DB=36.2
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 0, moop = 9250 WHERE contract_id='H1889' AND plan_id='005' AND segment_id='000';

-- H1889-034-000  UnitedHealthcare  UHC Dual Complete NC-S2 (PPO D-SNP)
--   premium: CMS=0  DB=36.2
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 0, moop = 9250 WHERE contract_id='H1889' AND plan_id='034' AND segment_id='000';

-- H1914-007-000  Wellcare  Wellcare Simple Open (PPO)
--   moop: CMS=4300  DB=8950
UPDATE pm_plans SET moop = 4300 WHERE contract_id='H1914' AND plan_id='007' AND segment_id='000';

-- H1914-008-000  Wellcare  Wellcare Dual Liberty Open (PPO D-SNP)
--   premium: CMS=0  DB=25.8
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 0, moop = 9250 WHERE contract_id='H1914' AND plan_id='008' AND segment_id='000';

-- H1914-009-000  Wellcare  Wellcare Assist Open (PPO)
--   premium: CMS=0  DB=31
--   moop: CMS=4201  DB=9550
UPDATE pm_plans SET monthly_premium = 0, moop = 4201 WHERE contract_id='H1914' AND plan_id='009' AND segment_id='000';

-- H1914-010-000  Wellcare  Wellcare Giveback Open (PPO)
--   moop: CMS=8300  DB=12450
UPDATE pm_plans SET moop = 8300 WHERE contract_id='H1914' AND plan_id='010' AND segment_id='000';

-- H1914-011-000  Wellcare  Wellcare Patriot Giveback Open (PPO)
--   moop: CMS=8850  DB=13300
UPDATE pm_plans SET moop = 8850 WHERE contract_id='H1914' AND plan_id='011' AND segment_id='000';

-- H2001-084-000  UnitedHealthcare  AARP Medicare Advantage Access from UHC NC-23 (PPO)
--   premium: CMS=102  DB=255
UPDATE pm_plans SET monthly_premium = 102 WHERE contract_id='H2001' AND plan_id='084' AND segment_id='000';

-- H2406-034-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0016 (PPO)
--   premium: CMS=0  DB=53
--   moop: CMS=4200  DB=6300
UPDATE pm_plans SET monthly_premium = 0, moop = 4200 WHERE contract_id='H2406' AND plan_id='034' AND segment_id='000';

-- H2406-098-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0017 (PPO)
--   moop: CMS=6200  DB=10100
UPDATE pm_plans SET moop = 6200 WHERE contract_id='H2406' AND plan_id='098' AND segment_id='000';

-- H3146-002-000  Aetna Medicare  Aetna Medicare Dual (HMO D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3146' AND plan_id='002' AND segment_id='000';

-- H3146-006-000  Aetna Medicare  Aetna Medicare Value Plus (HMO)
--   premium: CMS=0  DB=32.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3146' AND plan_id='006' AND segment_id='000';

-- H3146-022-000  Aetna Medicare  Aetna Medicare Full Dual Care (HMO D-SNP)
--   premium: CMS=0  DB=28.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3146' AND plan_id='022' AND segment_id='000';

-- H3146-039-000  Aetna Medicare  Aetna Medicare Enhanced (HMO)
--   premium: CMS=0  DB=63
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3146' AND plan_id='039' AND segment_id='000';

-- H3404-003-001  Blue Cross and Blue Shield of North Carolina  Blue Medicare PPO Enhanced (PPO)
--   premium: CMS=6  DB=35
UPDATE pm_plans SET monthly_premium = 6 WHERE contract_id='H3404' AND plan_id='003' AND segment_id='001';

-- H3404-004-000  Blue Cross and Blue Shield of North Carolina  Blue Medicare Freedom+ (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H3404' AND plan_id='004' AND segment_id='000';

-- H3449-024-001  Blue Cross and Blue Shield of North Carolina  Blue Medicare Enhanced (HMO-POS)
--   premium: CMS=19.6  DB=30
UPDATE pm_plans SET monthly_premium = 19.6 WHERE contract_id='H3449' AND plan_id='024' AND segment_id='001';

-- H4073-002-000  Wellcare  Wellcare Dual Access (HMO-POS D-SNP)
--   premium: CMS=0  DB=32.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4073' AND plan_id='002' AND segment_id='000';

-- H4073-003-000  Wellcare  Wellcare Dual Reserve (HMO-POS D-SNP)
--   premium: CMS=0  DB=27.5
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4073' AND plan_id='003' AND segment_id='000';

-- H4073-004-000  Wellcare  Wellcare Dual Liberty (HMO-POS D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4073' AND plan_id='004' AND segment_id='000';

-- H4172-001-000  NHC Advantage  NHC Advantage (HMO I-SNP)
--   premium: CMS=0  DB=31
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4172' AND plan_id='001' AND segment_id='000';

-- H5216-017-000  Humana  HumanaChoice Giveback H5216-017 (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5216' AND plan_id='017' AND segment_id='000';

-- H5216-211-000  Humana  HumanaChoice H5216-211 (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5216' AND plan_id='211' AND segment_id='000';

-- H5216-343-000  Humana  Humana USAA Honor Giveback (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5216' AND plan_id='343' AND segment_id='000';

-- H5253-037-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0021 (HMO-POS)
--   premium: CMS=0  DB=37
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5253' AND plan_id='037' AND segment_id='000';

-- H5253-041-000  UnitedHealthcare  UHC Dual Complete NC-D001 (HMO-POS D-SNP)
--   premium: CMS=0  DB=25.3
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5253' AND plan_id='041' AND segment_id='000';

-- H5253-116-000  UnitedHealthcare  UHC Dual Complete NC-V001 (HMO-POS D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5253' AND plan_id='116' AND segment_id='000';

-- H5253-184-000  UnitedHealthcare  UHC Dual Complete NC-S3 (HMO-POS D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5253' AND plan_id='184' AND segment_id='000';

-- H5299-006-000  Devoted Health  DEVOTED DUAL PLUS 006 NC (HMO D-SNP)
--   premium: CMS=0  DB=35
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='006' AND segment_id='000';

-- H5299-009-000  Devoted Health  DEVOTED DUAL 009 NC (HMO D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='009' AND segment_id='000';

-- H5299-013-000  Devoted Health  DEVOTED DUAL FULL 013 NC (HMO D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='013' AND segment_id='000';

-- H5299-015-000  Devoted Health  DEVOTED C-SNP PLUS 015 NC (HMO C-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='015' AND segment_id='000';

-- H5299-017-000  Devoted Health  DEVOTED C-SNP PREMIUM 017 NC (HMO C-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='017' AND segment_id='000';

-- H5374-001-000  Longevity Health Plan  Longevity Health Plan (HMO I-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5374' AND plan_id='001' AND segment_id='000';

-- H5521-081-000  Aetna Medicare  Aetna Medicare Signature (PPO)
--   moop: CMS=5900  DB=6900
UPDATE pm_plans SET moop = 5900 WHERE contract_id='H5521' AND plan_id='081' AND segment_id='000';

-- H5521-170-000  Aetna Medicare  Aetna Medicare Signature Extra (PPO)
--   moop: CMS=5900  DB=6900
UPDATE pm_plans SET moop = 5900 WHERE contract_id='H5521' AND plan_id='170' AND segment_id='000';

-- H5521-241-000  Aetna Medicare  Aetna Medicare Eagle Giveback (PPO)
--   moop: CMS=6750  DB=7750
UPDATE pm_plans SET moop = 6750 WHERE contract_id='H5521' AND plan_id='241' AND segment_id='000';

-- H5521-348-000  Aetna Medicare  Aetna Medicare Signature Giveback (PPO)
--   moop: CMS=7500  DB=8500
UPDATE pm_plans SET moop = 7500 WHERE contract_id='H5521' AND plan_id='348' AND segment_id='000';

-- H5525-035-000  Humana  HumanaChoice Giveback H5525-035 (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5525' AND plan_id='035' AND segment_id='000';

-- H5525-036-000  Humana  HumanaChoice SNP-DE H5525-036 (PPO D-SNP)
--   premium: CMS=0  DB=30.4
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 0, moop = 9250 WHERE contract_id='H5525' AND plan_id='036' AND segment_id='000';

-- H5525-050-000  Humana  HumanaChoice H5525-050 (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5525' AND plan_id='050' AND segment_id='000';

-- H5525-065-000  Humana  Humana USAA Honor Giveback (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5525' AND plan_id='065' AND segment_id='000';

-- H5525-070-000  Humana  HumanaChoice H5525-070 (PPO)
--   premium: CMS=0  DB=24
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 0, moop = 9250 WHERE contract_id='H5525' AND plan_id='070' AND segment_id='000';

-- H5525-072-000  Humana  Humana Dual Select H5525-072 (PPO D-SNP)
--   premium: CMS=0  DB=33.5
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 0, moop = 9250 WHERE contract_id='H5525' AND plan_id='072' AND segment_id='000';

-- H5525-083-000  Humana  HumanaChoice H5525-083 (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5525' AND plan_id='083' AND segment_id='000';

-- H6351-001-000  Liberty Medicare Advantage  Liberty Medicare Advantage Nursing Home Plan (HMO I-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H6351' AND plan_id='001' AND segment_id='000';

-- H6351-005-000  Liberty Medicare Advantage  Liberty Medicare Dual Plan (HMO D-SNP)
--   premium: CMS=0  DB=14.7
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H6351' AND plan_id='005' AND segment_id='000';

-- H7849-113-004  HealthSpring  HealthSpring True Choice (PPO)
--   moop: CMS=5450  DB=10100
UPDATE pm_plans SET moop = 5450 WHERE contract_id='H7849' AND plan_id='113' AND segment_id='004';

-- H9147-001-000  Blue Cross and Blue Shield of North Carolina  Healthy Blue + Medicare (HMO-POS D-SNP)
--   premium: CMS=0  DB=18.7
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9147' AND plan_id='001' AND segment_id='000';

-- H9700-003-000  Devoted Health  DEVOTED CHOICE 003 NC (PPO)
--   moop: CMS=4500  DB=5900
UPDATE pm_plans SET moop = 4500 WHERE contract_id='H9700' AND plan_id='003' AND segment_id='000';

-- H9700-004-000  Devoted Health  DEVOTED CHOICE GIVEBACK 004 NC (PPO)
--   moop: CMS=8000  DB=10000
UPDATE pm_plans SET moop = 8000 WHERE contract_id='H9700' AND plan_id='004' AND segment_id='000';

-- H9700-007-000  Devoted Health  DEVOTED CHOICE MA ONLY 007 NC (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H9700' AND plan_id='007' AND segment_id='000';

-- H9725-003-000  HealthSpring  HealthSpring TotalCare (HMO D-SNP)
--   premium: CMS=0  DB=19.7
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9725' AND plan_id='003' AND segment_id='000';

-- H9725-013-000  HealthSpring  HealthSpring TotalCare Plus (HMO D-SNP)
--   premium: CMS=0  DB=28.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9725' AND plan_id='013' AND segment_id='000';

-- H9725-017-004  HealthSpring  HealthSpring Preferred Plus (HMO)
--   premium: CMS=0  DB=14
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9725' AND plan_id='017' AND segment_id='004';

-- H9808-004-000  HealthTeam Advantage  HealthTeam Advantage Plan I (PPO)
--   moop: CMS=3900  DB=6300
UPDATE pm_plans SET moop = 3900 WHERE contract_id='H9808' AND plan_id='004' AND segment_id='000';

-- H9808-005-000  HealthTeam Advantage  HealthTeam Advantage Plan II (PPO)
--   premium: CMS=0  DB=40
--   moop: CMS=3700  DB=6300
UPDATE pm_plans SET monthly_premium = 0, moop = 3700 WHERE contract_id='H9808' AND plan_id='005' AND segment_id='000';

-- H9808-009-000  HealthTeam Advantage  HealthTeam Advantage Eagle Plan (PPO)
--   moop: CMS=4500  DB=7500
UPDATE pm_plans SET moop = 4500 WHERE contract_id='H9808' AND plan_id='009' AND segment_id='000';

-- H9808-010-000  HealthTeam Advantage  HealthTeam Advantage Vitality Plan (PPO)
--   moop: CMS=4200  DB=6300
UPDATE pm_plans SET moop = 4200 WHERE contract_id='H9808' AND plan_id='010' AND segment_id='000';

-- R0110-004-000  Humana  HumanaChoice R0110-004 (Regional PPO)
--   moop: CMS=7000  DB=13900
UPDATE pm_plans SET moop = 7000 WHERE contract_id='R0110' AND plan_id='004' AND segment_id='000';

-- R0110-005-000  Humana  Humana Full Access R0110-005 (Regional PPO)
--   premium: CMS=34.8  DB=117
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET monthly_premium = 34.8, moop = 9250 WHERE contract_id='R0110' AND plan_id='005' AND segment_id='000';

-- R0110-006-000  Humana  Humana USAA Honor Giveback (Regional PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='R0110' AND plan_id='006' AND segment_id='000';

-- H3404-003-002  Blue Cross and Blue Shield of North Carolina  Blue Medicare PPO Enhanced (PPO)
--   premium: CMS=22.6  DB=53
UPDATE pm_plans SET monthly_premium = 22.6 WHERE contract_id='H3404' AND plan_id='003' AND segment_id='002';

-- H3449-024-002  Blue Cross and Blue Shield of North Carolina  Blue Medicare Enhanced (HMO-POS)
--   premium: CMS=29.6  DB=40
UPDATE pm_plans SET monthly_premium = 29.6 WHERE contract_id='H3449' AND plan_id='024' AND segment_id='002';

-- H4676-002-000  Troy Medicare  Troy Medicare for Dual-eligible Beneficiaries (HMO D-SNP)
--   premium: CMS=0  DB=31.3
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4676' AND plan_id='002' AND segment_id='000';

-- H5299-016-000  Devoted Health  DEVOTED C-SNP PREMIUM 016 NC (HMO C-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='016' AND segment_id='000';

-- H7849-113-001  HealthSpring  HealthSpring True Choice (PPO)
--   moop: CMS=5700  DB=10100
UPDATE pm_plans SET moop = 5700 WHERE contract_id='H7849' AND plan_id='113' AND segment_id='001';

-- H9700-001-000  Devoted Health  DEVOTED CHOICE 001 NC (PPO)
--   moop: CMS=5400  DB=6900
UPDATE pm_plans SET moop = 5400 WHERE contract_id='H9700' AND plan_id='001' AND segment_id='000';

-- H9700-002-000  Devoted Health  DEVOTED CHOICE GIVEBACK 002 NC (PPO)
--   moop: CMS=8000  DB=10000
UPDATE pm_plans SET moop = 8000 WHERE contract_id='H9700' AND plan_id='002' AND segment_id='000';

-- H9725-017-001  HealthSpring  HealthSpring Preferred Plus (HMO)
--   premium: CMS=0  DB=13
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9725' AND plan_id='017' AND segment_id='001';

-- S4802-081-000  Wellcare  Wellcare Classic (PDP)
--   premium: CMS=4.7  DB=null
UPDATE pm_plans SET monthly_premium = 4.7 WHERE contract_id='S4802' AND plan_id='081' AND segment_id='000';

-- S4802-143-000  Wellcare  Wellcare Value Script (PDP)
--   premium: CMS=3.6  DB=null
UPDATE pm_plans SET monthly_premium = 3.6 WHERE contract_id='S4802' AND plan_id='143' AND segment_id='000';

-- S5540-002-000  Blue Cross and Blue Shield of North Carolina  Blue Medicare Rx Standard (PDP)
--   premium: CMS=83.9  DB=null
UPDATE pm_plans SET monthly_premium = 83.9 WHERE contract_id='S5540' AND plan_id='002' AND segment_id='000';

-- S5540-004-000  Blue Cross and Blue Shield of North Carolina  Blue Medicare Rx Enhanced (PDP)
--   premium: CMS=163.2  DB=null
UPDATE pm_plans SET monthly_premium = 163.2 WHERE contract_id='S5540' AND plan_id='004' AND segment_id='000';

-- S5601-016-000  Aetna Medicare  SilverScript Choice (PDP)
--   premium: CMS=90.2  DB=null
UPDATE pm_plans SET monthly_premium = 90.2 WHERE contract_id='S5601' AND plan_id='016' AND segment_id='000';

-- S5617-217-000  HealthSpring  HealthSpring Assurance Rx (PDP)
--   premium: CMS=110.4  DB=null
UPDATE pm_plans SET monthly_premium = 110.4 WHERE contract_id='S5617' AND plan_id='217' AND segment_id='000';

-- S5617-358-000  HealthSpring  HealthSpring Extra Rx (PDP)
--   premium: CMS=78  DB=null
UPDATE pm_plans SET monthly_premium = 78 WHERE contract_id='S5617' AND plan_id='358' AND segment_id='000';

-- S5884-133-000  Humana  Humana Basic Rx Plan (PDP)
--   premium: CMS=6.8  DB=null
UPDATE pm_plans SET monthly_premium = 6.8 WHERE contract_id='S5884' AND plan_id='133' AND segment_id='000';

-- S5884-154-000  Humana  Humana Premier Rx Plan (PDP)
--   premium: CMS=110.9  DB=null
UPDATE pm_plans SET monthly_premium = 110.9 WHERE contract_id='S5884' AND plan_id='154' AND segment_id='000';

-- S5884-187-000  Humana  Humana Value Rx Plan (PDP)
--   premium: CMS=32  DB=null
UPDATE pm_plans SET monthly_premium = 32 WHERE contract_id='S5884' AND plan_id='187' AND segment_id='000';

-- S5921-353-000  UnitedHealthcare  AARP Medicare Rx Saver from UHC (PDP)
--   premium: CMS=56.9  DB=null
UPDATE pm_plans SET monthly_premium = 56.9 WHERE contract_id='S5921' AND plan_id='353' AND segment_id='000';

-- S5921-390-000  UnitedHealthcare  AARP Medicare Rx Preferred from UHC (PDP)
--   premium: CMS=119.8  DB=null
UPDATE pm_plans SET monthly_premium = 119.8 WHERE contract_id='S5921' AND plan_id='390' AND segment_id='000';

-- H2001-103-000  UnitedHealthcare  AARP Medicare Advantage Patriot No Rx NC-MA01 (PPO)
--   moop: CMS=8900  DB=13900
UPDATE pm_plans SET moop = 8900 WHERE contract_id='H2001' AND plan_id='103' AND segment_id='000';

-- H3449-024-003  Blue Cross and Blue Shield of North Carolina  Blue Medicare Enhanced (HMO-POS)
--   premium: CMS=36.6  DB=47
UPDATE pm_plans SET monthly_premium = 36.6 WHERE contract_id='H3449' AND plan_id='024' AND segment_id='003';

-- H5299-014-000  Devoted Health  DEVOTED C-SNP PREMIUM 014 NC (HMO C-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='014' AND segment_id='000';

-- H5521-139-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=0  DB=21
--   moop: CMS=6750  DB=7750
UPDATE pm_plans SET monthly_premium = 0, moop = 6750 WHERE contract_id='H5521' AND plan_id='139' AND segment_id='000';

-- H6622-026-000  Humana  Humana Gold Plus H6622-026 (HMO-POS)
--   premium: CMS=0  DB=34.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H6622' AND plan_id='026' AND segment_id='000';

-- H7849-113-003  HealthSpring  HealthSpring True Choice (PPO)
--   moop: CMS=4900  DB=10100
UPDATE pm_plans SET moop = 4900 WHERE contract_id='H7849' AND plan_id='113' AND segment_id='003';

-- H9700-008-000  Devoted Health  DEVOTED CHOICE 008 NC (PPO)
--   moop: CMS=5900  DB=7900
UPDATE pm_plans SET moop = 5900 WHERE contract_id='H9700' AND plan_id='008' AND segment_id='000';

-- H9700-009-000  Devoted Health  DEVOTED CHOICE GIVEBACK 009 NC (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H9700' AND plan_id='009' AND segment_id='000';

-- H9725-017-003  HealthSpring  HealthSpring Preferred Plus (HMO)
--   premium: CMS=0  DB=14
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9725' AND plan_id='017' AND segment_id='003';

-- H2001-090-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0001 (PPO)
--   moop: CMS=6700  DB=10100
UPDATE pm_plans SET moop = 6700 WHERE contract_id='H2001' AND plan_id='090' AND segment_id='000';

-- H2001-102-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0004 (PPO)
--   premium: CMS=0  DB=29
--   moop: CMS=6200  DB=10100
UPDATE pm_plans SET monthly_premium = 0, moop = 6200 WHERE contract_id='H2001' AND plan_id='102' AND segment_id='000';

-- H5253-080-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0009 (HMO-POS)
--   premium: CMS=0  DB=48
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5253' AND plan_id='080' AND segment_id='000';

-- H5296-004-000  Alignment Health Plan  Alignment Health NC Duals (HMO-POS D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5296' AND plan_id='004' AND segment_id='000';

-- H5296-009-000  Alignment Health Plan  Alignment Health Heart & Diabetes NCPlus (HMO-POS C-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5296' AND plan_id='009' AND segment_id='000';

-- H5299-018-000  Devoted Health  DEVOTED C-SNP PREMIUM 018 NC (HMO C-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5299' AND plan_id='018' AND segment_id='000';

-- H5521-236-000  Aetna Medicare  Aetna Medicare Signature (PPO)
--   moop: CMS=6750  DB=7750
UPDATE pm_plans SET moop = 6750 WHERE contract_id='H5521' AND plan_id='236' AND segment_id='000';

-- H7074-001-000  Alignment Health Plan  Alignment Health AVA (PPO)
--   premium: CMS=0  DB=10
--   moop: CMS=3900  DB=6200
UPDATE pm_plans SET monthly_premium = 0, moop = 3900 WHERE contract_id='H7074' AND plan_id='001' AND segment_id='000';

-- H7849-113-002  HealthSpring  HealthSpring True Choice (PPO)
--   moop: CMS=4350  DB=10100
UPDATE pm_plans SET moop = 4350 WHERE contract_id='H7849' AND plan_id='113' AND segment_id='002';

-- H9700-005-000  Devoted Health  DEVOTED CHOICE 005 NC (PPO)
--   moop: CMS=5300  DB=8950
UPDATE pm_plans SET moop = 5300 WHERE contract_id='H9700' AND plan_id='005' AND segment_id='000';

-- H9700-006-000  Devoted Health  DEVOTED CHOICE GIVEBACK 006 NC (PPO)
--   moop: CMS=8000  DB=10000
UPDATE pm_plans SET moop = 8000 WHERE contract_id='H9700' AND plan_id='006' AND segment_id='000';

-- H9725-017-002  HealthSpring  HealthSpring Preferred Plus (HMO)
--   premium: CMS=0  DB=11
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9725' AND plan_id='017' AND segment_id='002';

-- H5521-243-000  Aetna Medicare  Aetna Medicare Signature (PPO)
--   moop: CMS=6750  DB=7750
UPDATE pm_plans SET moop = 6750 WHERE contract_id='H5521' AND plan_id='243' AND segment_id='000';

-- H5521-169-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=0  DB=20
--   moop: CMS=5900  DB=6900
UPDATE pm_plans SET monthly_premium = 0, moop = 5900 WHERE contract_id='H5521' AND plan_id='169' AND segment_id='000';

-- H5525-034-000  Humana  Humana Full Access H5525-034 (PPO)
--   moop: CMS=9250  DB=13900
UPDATE pm_plans SET moop = 9250 WHERE contract_id='H5525' AND plan_id='034' AND segment_id='000';

-- H6622-027-000  Humana  Humana Dual Select H6622-027 (HMO-POS D-SNP)
--   premium: CMS=0  DB=29
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H6622' AND plan_id='027' AND segment_id='000';

-- H8212-001-000  AmeriHealth Caritas VIP Care  AmeriHealth Caritas VIP Care (HMO D-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8212' AND plan_id='001' AND segment_id='000';

-- H3146-044-000  Aetna Medicare  Aetna Medicare Chronic Care Value (HMO C-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3146' AND plan_id='044' AND segment_id='000';

-- H4439-001-000  Provider Partners Health Plans  Provider Partners North Carolina Advantage Plan (HMO I-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4439' AND plan_id='001' AND segment_id='000';

-- H4439-003-000  Provider Partners Health Plans  Provider Partners North Carolina Essential Plan (HMO I-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4439' AND plan_id='003' AND segment_id='000';

-- H6345-001-000  PruittHealth Premier  PruittHealth Premier (HMO I-SNP)
--   premium: CMS=0  DB=36.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H6345' AND plan_id='001' AND segment_id='000';

-- H2406-115-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0019 (PPO)
--   premium: CMS=0  DB=25
--   moop: CMS=6700  DB=10100
UPDATE pm_plans SET monthly_premium = 0, moop = 6700 WHERE contract_id='H2406' AND plan_id='115' AND segment_id='000';

-- H5521-609-000  Aetna Medicare  Aetna Medicare Signature (PPO)
--   moop: CMS=6750  DB=7750
UPDATE pm_plans SET moop = 6750 WHERE contract_id='H5521' AND plan_id='609' AND segment_id='000';

-- H5253-104-000  UnitedHealthcare  AARP Medicare Advantage from UHC NC-0012 (HMO-POS)
--   premium: CMS=0  DB=54
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5253' AND plan_id='104' AND segment_id='000';

-- H5652-001-000  UnitedHealthcare  Erickson Advantage Signature (HMO-POS)
--   premium: CMS=8.3  DB=182
UPDATE pm_plans SET monthly_premium = 8.3 WHERE contract_id='H5652' AND plan_id='001' AND segment_id='000';

-- H5652-004-000  UnitedHealthcare  Erickson Advantage Champion (HMO-POS C-SNP)
--   premium: CMS=62.5  DB=182
UPDATE pm_plans SET monthly_premium = 62.5 WHERE contract_id='H5652' AND plan_id='004' AND segment_id='000';

-- H5652-006-000  UnitedHealthcare  Erickson Advantage Freedom (HMO-POS)
--   premium: CMS=0  DB=89
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5652' AND plan_id='006' AND segment_id='000';

-- H5652-008-000  UnitedHealthcare  Erickson Advantage Liberty (HMO-POS)
--   premium: CMS=0  DB=14
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5652' AND plan_id='008' AND segment_id='000';

-- S4802-013-000  Wellcare  Wellcare Classic (PDP)
--   premium: CMS=0  DB=null
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='S4802' AND plan_id='013' AND segment_id='000';

-- S4802-155-000  Wellcare  Wellcare Value Script (PDP)
--   premium: CMS=0  DB=null
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='S4802' AND plan_id='155' AND segment_id='000';

-- S5601-044-000  Aetna Medicare  SilverScript Choice (PDP)
--   premium: CMS=94.8  DB=null
UPDATE pm_plans SET monthly_premium = 94.8 WHERE contract_id='S5601' AND plan_id='044' AND segment_id='000';

-- S5617-108-000  HealthSpring  HealthSpring Assurance Rx (PDP)
--   premium: CMS=111.4  DB=null
UPDATE pm_plans SET monthly_premium = 111.4 WHERE contract_id='S5617' AND plan_id='108' AND segment_id='000';

-- S5617-372-000  HealthSpring  HealthSpring Extra Rx (PDP)
--   premium: CMS=70  DB=null
UPDATE pm_plans SET monthly_premium = 70 WHERE contract_id='S5617' AND plan_id='372' AND segment_id='000';

-- S5715-005-000  HealthSpring  Blue Cross MedicareRx Value (PDP)
--   premium: CMS=167.4  DB=null
--   carrier: CMS="HealthSpring"  DB="Blue Cross and Blue Shield of IL, NM, OK, TX"
UPDATE pm_plans SET monthly_premium = 167.4, carrier = 'HealthSpring' WHERE contract_id='S5715' AND plan_id='005' AND segment_id='000';

-- S5715-014-000  HealthSpring  Blue Cross MedicareRx Basic (PDP)
--   premium: CMS=104.7  DB=null
--   carrier: CMS="HealthSpring"  DB="Blue Cross and Blue Shield of IL, NM, OK, TX"
UPDATE pm_plans SET monthly_premium = 104.7, carrier = 'HealthSpring' WHERE contract_id='S5715' AND plan_id='014' AND segment_id='000';

-- S5884-143-000  Humana  Humana Basic Rx Plan (PDP)
--   premium: CMS=41.7  DB=null
UPDATE pm_plans SET monthly_premium = 41.7 WHERE contract_id='S5884' AND plan_id='143' AND segment_id='000';

-- S5884-168-000  Humana  Humana Premier Rx Plan (PDP)
--   premium: CMS=118.2  DB=null
UPDATE pm_plans SET monthly_premium = 118.2 WHERE contract_id='S5884' AND plan_id='168' AND segment_id='000';

-- S5884-201-000  Humana  Humana Value Rx Plan (PDP)
--   premium: CMS=22.9  DB=null
UPDATE pm_plans SET monthly_premium = 22.9 WHERE contract_id='S5884' AND plan_id='201' AND segment_id='000';

-- S5921-367-000  UnitedHealthcare  AARP Medicare Rx Saver from UHC (PDP)
--   premium: CMS=89.2  DB=null
UPDATE pm_plans SET monthly_premium = 89.2 WHERE contract_id='S5921' AND plan_id='367' AND segment_id='000';

-- S5921-403-000  UnitedHealthcare  AARP Medicare Rx Preferred from UHC (PDP)
--   premium: CMS=114.8  DB=null
UPDATE pm_plans SET monthly_premium = 114.8 WHERE contract_id='S5921' AND plan_id='403' AND segment_id='000';

-- H4054-001-000  Provider Partners Health Plans  Provider Partners Texas Advantage Plan (HMO I-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4054' AND plan_id='001' AND segment_id='000';

-- H5216-042-000  Humana  HumanaChoice H5216-042 (PPO)
--   premium: CMS=0  DB=60
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='042' AND segment_id='000';

-- H5216-043-005  Humana  HumanaChoice H5216-043 (PPO)
--   premium: CMS=0  DB=15
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='043' AND segment_id='005';

-- H6891-001-000  American Health Advantage of Texas  American Health Advantage of Texas (HMO I-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H6891' AND plan_id='001' AND segment_id='000';

-- H8634-026-000  Blue Cross and Blue Shield of IL, NM, OK, TX  Blue Cross Medicare Advantage Protect (PPO)
--   drug_deductible: CMS=750  DB=null
UPDATE pm_plans SET drug_deductible = 750 WHERE contract_id='H8634' AND plan_id='026' AND segment_id='000';

-- H8849-010-002  Wellpoint  Wellpoint Full Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=2.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='010' AND segment_id='002';

-- H8849-011-002  Wellpoint  Wellpoint Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='011' AND segment_id='002';

-- H9706-002-000  Blue Cross and Blue Shield of Texas  Blue Cross Medicare Advantage Dual Care Plus (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9706' AND plan_id='002' AND segment_id='000';

-- R4182-003-000  Humana  HumanaChoice R4182-003 (Regional PPO)
--   premium: CMS=0  DB=97
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='R4182' AND plan_id='003' AND segment_id='000';

-- R4182-004-000  Humana  HumanaChoice R4182-004 (Regional PPO)
--   premium: CMS=3.9  DB=44
UPDATE pm_plans SET monthly_premium = 3.9 WHERE contract_id='R4182' AND plan_id='004' AND segment_id='000';

-- R6801-009-000  UnitedHealthcare  UHC Complete Care TX-29 (Regional PPO C-SNP)
--   premium: CMS=9.1  DB=57
UPDATE pm_plans SET monthly_premium = 9.1 WHERE contract_id='R6801' AND plan_id='009' AND segment_id='000';

-- R6801-011-000  UnitedHealthcare  UHC Dual Complete TX-S001 (Regional PPO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='R6801' AND plan_id='011' AND segment_id='000';

-- R6801-012-000  UnitedHealthcare  UHC Medicare Advantage TX-0030 (Regional PPO)
--   premium: CMS=14.6  DB=102
UPDATE pm_plans SET monthly_premium = 14.6 WHERE contract_id='R6801' AND plan_id='012' AND segment_id='000';

-- H0174-004-000  Wellcare  Wellcare Dual Access (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='004' AND segment_id='000';

-- H0174-022-000  Wellcare  Wellcare Dual Reserve (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='022' AND segment_id='000';

-- H0174-026-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='026' AND segment_id='000';

-- H7617-027-000  Humana  HumanaChoice H7617-027 (PPO)
--   premium: CMS=10.2  DB=36
UPDATE pm_plans SET monthly_premium = 10.2 WHERE contract_id='H7617' AND plan_id='027' AND segment_id='000';

-- H8634-033-000  Blue Cross and Blue Shield of IL, NM, OK, TX  Blue Cross Medicare Advantage Preferred (PPO)
--   premium: CMS=37.3  DB=110
UPDATE pm_plans SET monthly_premium = 37.3 WHERE contract_id='H8634' AND plan_id='033' AND segment_id='000';

-- H8849-010-001  Wellpoint  Wellpoint Full Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=2.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='010' AND segment_id='001';

-- H8849-011-001  Wellpoint  Wellpoint Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='011' AND segment_id='001';

-- H0028-036-000  Humana  Humana Gold Plus SNP-DE H0028-036 (HMO D-SNP)
--   premium: CMS=0  DB=2.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0028' AND plan_id='036' AND segment_id='000';

-- H0028-070-000  Humana  Humana Gold Plus H0028-070 (HMO)
--   premium: CMS=4.5  DB=14
UPDATE pm_plans SET monthly_premium = 4.5 WHERE contract_id='H0028' AND plan_id='070' AND segment_id='000';

-- H4461-053-000  Humana  Humana Gold Plus H4461-053 (HMO)
--   premium: CMS=6.3  DB=14
UPDATE pm_plans SET monthly_premium = 6.3 WHERE contract_id='H4461' AND plan_id='053' AND segment_id='000';

-- H4461-069-000  Humana  Humana Gold Plus SNP-DE H4461-069 (HMO D-SNP)
--   premium: CMS=0  DB=2.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4461' AND plan_id='069' AND segment_id='000';

-- H4523-041-000  Aetna Medicare  Aetna Medicare Partial Dual Care (HMO D-SNP)
--   premium: CMS=0  DB=4.6
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4523' AND plan_id='041' AND segment_id='000';

-- H5015-001-000  Texas Independence Health Plan  Texas Independence Health Plan, Inc. (HMO I-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5015' AND plan_id='001' AND segment_id='000';

-- H5015-002-000  Texas Independence Health Plan  Texas Independence Community Plan (HMO I-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5015' AND plan_id='002' AND segment_id='000';

-- H5216-043-001  Humana  HumanaChoice H5216-043 (PPO)
--   premium: CMS=0  DB=20
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5216' AND plan_id='043' AND segment_id='001';

-- H5294-010-000  Wellcare  Wellcare Dual Liberty (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='010' AND segment_id='000';

-- H5294-015-000  Wellcare  Wellcare Dual Access (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='015' AND segment_id='000';

-- H5294-022-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='022' AND segment_id='000';

-- H7617-059-000  Humana  HumanaChoice H7617-059 (PPO)
--   premium: CMS=0  DB=20
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7617' AND plan_id='059' AND segment_id='000';

-- H5294-016-000  Wellcare  Wellcare Assist (HMO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='016' AND segment_id='000';

-- H5294-025-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='025' AND segment_id='000';

-- H0609-071-000  UnitedHealthcare  AARP Medicare Advantage from UHC TX-0043 (HMO-POS)
--   premium: CMS=3.1  DB=27
UPDATE pm_plans SET monthly_premium = 3.1 WHERE contract_id='H0609' AND plan_id='071' AND segment_id='000';

-- H1666-023-000  Blue Cross and Blue Shield of NM, TX  Blue Cross Medicare Advantage Balance (PPO)
--   premium: CMS=11.5  DB=77
UPDATE pm_plans SET monthly_premium = 11.5 WHERE contract_id='H1666' AND plan_id='023' AND segment_id='000';

-- H1666-024-000  Blue Cross and Blue Shield of NM, TX  Blue Cross Medicare Advantage Optimum (PPO)
--   premium: CMS=79.8  DB=142
UPDATE pm_plans SET monthly_premium = 79.8 WHERE contract_id='H1666' AND plan_id='024' AND segment_id='000';

-- H2593-051-000  Wellpoint  Wellpoint Full Dual Advantage 2 (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2593' AND plan_id='051' AND segment_id='000';

-- H3288-048-000  Aetna Medicare  Aetna Medicare Value Plus (PPO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='048' AND segment_id='000';

-- H3467-001-000  ProCare Advantage  ProCare Advantage (HMO-POS I-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3467' AND plan_id='001' AND segment_id='000';

-- H5447-002-000  Community First  Community First Medicare Advantage D-SNP (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5447' AND plan_id='002' AND segment_id='000';

-- H7993-012-000  Devoted Health  DEVOTED DUAL 012 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='012' AND segment_id='000';

-- H7993-033-000  Devoted Health  DEVOTED C-SNP PLUS 033 TX (HMO C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='033' AND segment_id='000';

-- H7993-041-000  Devoted Health  DEVOTED DUAL FULL 041 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='041' AND segment_id='000';

-- H8849-011-003  Wellpoint  Wellpoint Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='011' AND segment_id='003';

-- H0174-006-000  Wellcare  Wellcare Dual Liberty (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='006' AND segment_id='000';

-- H0174-009-000  Wellcare  Wellcare Assist (HMO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='009' AND segment_id='000';

-- H2593-048-000  Wellpoint  Wellpoint Full Dual Advantage 2 (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2593' AND plan_id='048' AND segment_id='000';

-- H3288-018-000  Aetna Medicare  Aetna Medicare Value Plus (PPO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='018' AND segment_id='000';

-- H4523-043-000  Aetna Medicare  Aetna Medicare Partial Dual Care (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4523' AND plan_id='043' AND segment_id='000';

-- H9826-003-000  Community Health Choice  Community DualCare Aligned (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9826' AND plan_id='003' AND segment_id='000';

-- H8849-010-005  Wellpoint  Wellpoint Full Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=2.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='010' AND segment_id='005';

-- H8849-011-005  Wellpoint  Wellpoint Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='011' AND segment_id='005';

-- H8145-084-000  Humana  Humana Gold Choice H8145-084 (PFFS)
--   premium: CMS=0  DB=29
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8145' AND plan_id='084' AND segment_id='000';

-- H0174-024-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='024' AND segment_id='000';

-- H1666-003-000  Blue Cross and Blue Shield of NM, TX  Blue Cross Medicare Advantage Choice Premier (PPO)
--   premium: CMS=3.4  DB=96
UPDATE pm_plans SET monthly_premium = 3.4 WHERE contract_id='H1666' AND plan_id='003' AND segment_id='000';

-- H1666-022-000  Blue Cross and Blue Shield of NM, TX  Blue Cross Medicare Advantage Optimum (PPO)
--   premium: CMS=78.3  DB=142
UPDATE pm_plans SET monthly_premium = 78.3 WHERE contract_id='H1666' AND plan_id='022' AND segment_id='000';

-- H4527-052-000  UnitedHealthcare  AARP Medicare Advantage from UHC TX-46 (HMO-POS)
--   premium: CMS=0  DB=21
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4527' AND plan_id='052' AND segment_id='000';

-- H8142-002-000  Baylor Scott & White Health Plan  BSW SeniorCare Advantage Preferred Rx (HMO-POS)
--   premium: CMS=139.1  DB=143
UPDATE pm_plans SET monthly_premium = 139.1 WHERE contract_id='H8142' AND plan_id='002' AND segment_id='000';

-- H8142-009-000  Baylor Scott & White Health Plan  BSW SeniorCare Advantage Essentials (HMO-POS)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8142' AND plan_id='009' AND segment_id='000';

-- H5294-013-000  Wellcare  Wellcare Assist (HMO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='013' AND segment_id='000';

-- H0174-025-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='025' AND segment_id='000';

-- H0710-020-000  UnitedHealthcare  UHC Nursing Home Plan TX-F001 (PPO I-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0710' AND plan_id='020' AND segment_id='000';

-- H2032-003-000  Baylor Scott & White Health Plan  BSW SeniorCare Advantage Platinum (PPO)
--   premium: CMS=120.7  DB=135
UPDATE pm_plans SET monthly_premium = 120.7 WHERE contract_id='H2032' AND plan_id='003' AND segment_id='000';

-- H3288-001-000  Aetna Medicare  Aetna Medicare Value Plus (PPO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='001' AND segment_id='000';

-- H7993-015-000  Devoted Health  DEVOTED DUAL 015 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='015' AND segment_id='000';

-- H7993-023-000  Devoted Health  DEVOTED C-SNP PREMIUM 023 TX (HMO C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='023' AND segment_id='000';

-- H7993-024-000  Devoted Health  DEVOTED C-SNP PLUS 024 TX (HMO C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='024' AND segment_id='000';

-- H7993-037-000  Devoted Health  DEVOTED DUAL FULL 037 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='037' AND segment_id='000';

-- H0609-059-000  UnitedHealthcare  AARP Medicare Advantage from UHC TX-25 (HMO-POS)
--   premium: CMS=7.1  DB=74
UPDATE pm_plans SET monthly_premium = 7.1 WHERE contract_id='H0609' AND plan_id='059' AND segment_id='000';

-- H5294-024-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='024' AND segment_id='000';

-- H4514-022-000  UnitedHealthcare  AARP Medicare Advantage from UHC TX-4P (HMO-POS)
--   premium: CMS=0  DB=34
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4514' AND plan_id='022' AND segment_id='000';

-- H7115-005-000  Memorial Hermann Health Plan  Memorial Hermann Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7115' AND plan_id='005' AND segment_id='000';

-- H4527-058-000  UnitedHealthcare  AARP Medicare Advantage from UHC TX-51 (HMO-POS)
--   premium: CMS=13.1  DB=24
UPDATE pm_plans SET monthly_premium = 13.1 WHERE contract_id='H4527' AND plan_id='058' AND segment_id='000';

-- H7680-007-000  Prominence Health Plan  Prominence Dual (HMO D-SNP)
--   premium: CMS=0  DB=4.2
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7680' AND plan_id='007' AND segment_id='000';

-- H3288-009-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=0  DB=45
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='009' AND segment_id='000';

-- H5294-021-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='021' AND segment_id='000';

-- H5294-023-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5294' AND plan_id='023' AND segment_id='000';

-- H7993-002-000  Devoted Health  DEVOTED PREMIUM 002 TX (HMO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='002' AND segment_id='000';

-- H7993-010-000  Devoted Health  DEVOTED DUAL 010 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='010' AND segment_id='000';

-- H7993-030-000  Devoted Health  DEVOTED C-SNP PREMIUM 030 TX (HMO C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='030' AND segment_id='000';

-- H7993-031-000  Devoted Health  DEVOTED C-SNP PLUS 031 TX (HMO C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='031' AND segment_id='000';

-- H7993-040-000  Devoted Health  DEVOTED DUAL FULL 040 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='040' AND segment_id='000';

-- H9826-004-000  Community Health Choice  Community DualCare Access (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H9826' AND plan_id='004' AND segment_id='000';

-- H0174-023-000  Wellcare  Wellcare Dual Liberty Sync (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0174' AND plan_id='023' AND segment_id='000';

-- H2293-025-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=2.3  DB=50
UPDATE pm_plans SET monthly_premium = 2.3 WHERE contract_id='H2293' AND plan_id='025' AND segment_id='000';

-- H3288-002-000  Aetna Medicare  Aetna Medicare Value Plus (PPO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='002' AND segment_id='000';

-- H3467-002-000  ProCare Advantage  ProCare Advantage - Kidney Care (HMO-POS C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3467' AND plan_id='002' AND segment_id='000';

-- H4523-039-000  Aetna Medicare  Aetna Medicare Prime Chronic Total (HMO C-SNP)
--   premium: CMS=0  DB=3.9
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H4523' AND plan_id='039' AND segment_id='000';

-- H8142-010-000  Baylor Scott & White Health Plan  BSW SeniorCare Advantage Essentials (HMO-POS)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8142' AND plan_id='010' AND segment_id='000';

-- H7680-017-000  Prominence Health Plan  Prominence Dual (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7680' AND plan_id='017' AND segment_id='000';

-- H7680-018-000  Prominence Health Plan  Prominence Extra Help (HMO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7680' AND plan_id='018' AND segment_id='000';

-- H0062-011-000  Wellcare  Wellcare Superior HealthPlan Dual Align (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0062' AND plan_id='011' AND segment_id='000';

-- H2406-135-000  UnitedHealthcare  AARP Medicare Advantage from UHC EP-4 (PPO)
--   premium: CMS=0  DB=39
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H2406' AND plan_id='135' AND segment_id='000';

-- H3288-007-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=0  DB=40
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='007' AND segment_id='000';

-- H3407-001-000  El Paso Health Medicare Advantage  El Paso Health Medicare Advantage Dual (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3407' AND plan_id='001' AND segment_id='000';

-- H5472-004-000  Alignment Health Plan  Alignment Health Heart & Diabetes Plus (HMO-POS C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5472' AND plan_id='004' AND segment_id='000';

-- H5472-007-000  Alignment Health Plan  Alignment Health Dual Select+ (HMO-POS D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5472' AND plan_id='007' AND segment_id='000';

-- H5472-009-000  Alignment Health Plan  Alignment Health Total Dual+ (HMO-POS D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H5472' AND plan_id='009' AND segment_id='000';

-- H7993-017-000  Devoted Health  DEVOTED DUAL 017 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='017' AND segment_id='000';

-- H7993-028-000  Devoted Health  DEVOTED C-SNP PREMIUM 028 TX (HMO C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='028' AND segment_id='000';

-- H7993-029-000  Devoted Health  DEVOTED C-SNP PLUS 029 TX (HMO C-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='029' AND segment_id='000';

-- H7993-038-000  Devoted Health  DEVOTED DUAL FULL 038 TX (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H7993' AND plan_id='038' AND segment_id='000';

-- H8849-010-004  Wellpoint  Wellpoint Full Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=2.4
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='010' AND segment_id='004';

-- H8849-011-004  Wellpoint  Wellpoint Dual Advantage (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H8849' AND plan_id='011' AND segment_id='004';

-- H3288-003-000  Aetna Medicare  Aetna Medicare Value Plus (PPO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='003' AND segment_id='000';

-- H3288-047-000  Aetna Medicare  Aetna Medicare Enhanced (PPO)
--   premium: CMS=0  DB=45
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='047' AND segment_id='000';

-- H3868-001-000  UnitedHealthcare  UHC Dual Complete TX-Y1 (HMO-POS D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3868' AND plan_id='001' AND segment_id='000';

-- H0473-003-000  Humana  HumanaChoice H0473-003 (PPO)
--   premium: CMS=0  DB=91
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0473' AND plan_id='003' AND segment_id='000';

-- H3288-004-000  Aetna Medicare  Aetna Medicare Value Plus (PPO)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H3288' AND plan_id='004' AND segment_id='000';

-- H0062-012-000  Wellcare  Wellcare Superior HealthPlan Dual Align (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H0062' AND plan_id='012' AND segment_id='000';

-- H6515-005-000  Molina Healthcare of Texas, Inc.  Molina Medicare Complete Care Plus (HMO D-SNP)
--   premium: CMS=0  DB=4.8
UPDATE pm_plans SET monthly_premium = 0 WHERE contract_id='H6515' AND plan_id='005' AND segment_id='000';

-- ── Section 2: INSERT shells for plans missing from DB ────
-- pm_plans is per-county. For each missing plan we emit ONE
-- INSERT per (state, county) row the landscape carries.

-- ── Section 3: plans in DB but NOT in 2026 landscape ────
-- These look stale. NOT auto-deleted — review manually.


-- COMMIT;  -- uncomment when ready
-- ROLLBACK;

-- Summary: 318 UPDATEs, 0 new plans (0 plan-county rows), 0 stale plans flagged.