// Per-profile markdown narrative report.

import type {
  BeneficiaryProfile,
  FieldComparison,
  PlanComparison,
  ProfileReport,
} from '../types.js';

function fmtPct(n: number): string {
  return `${(n * 100).toFixed(2)}%`;
}

function fmtValue(v: unknown): string {
  if (v === null || v === undefined) return '_null_';
  if (typeof v === 'string') {
    if (v === '') return '_empty_';
    return v.replace(/\|/g, '\\|');
  }
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  try {
    return JSON.stringify(v).replace(/\|/g, '\\|');
  } catch {
    return String(v);
  }
}

function countCritical(comps: FieldComparison[]): number {
  return comps.filter((c) => c.status === 'FAIL' && c.severity === 'critical')
    .length;
}

function planSection(pc: PlanComparison): string {
  const lines: string[] = [];
  lines.push(`### ${pc.planName} (${pc.planKey})`);
  lines.push('');
  lines.push(
    `- Pass: **${pc.passCount}** · Conditional: **${pc.conditionalCount}** · Fail: **${pc.failCount}** · N/A: **${pc.naCount}**`,
  );
  lines.push(`- Unweighted parity: **${fmtPct(pc.unweightedParity)}**`);
  lines.push(`- Weighted score: **${fmtPct(pc.weightedScore)}**`);

  const criticals = pc.comparisons.filter(
    (c) => c.status === 'FAIL' && c.severity === 'critical',
  );
  if (criticals.length > 0) {
    lines.push(`- Critical failures: **${criticals.length}**`);
  }
  lines.push('');
  return lines.join('\n');
}

function criticalTable(criticals: FieldComparison[]): string {
  if (criticals.length === 0) {
    return '_No critical failures across any plan._\n';
  }
  const rows: string[] = [];
  rows.push('| Field | MPF | PM | Fail | Note |');
  rows.push('| --- | --- | --- | --- | --- |');
  const shown = criticals.slice(0, 20);
  for (const c of shown) {
    rows.push(
      `| \`${c.fieldPath}\` | ${fmtValue(c.mpfValue)} | ${fmtValue(c.pmValue)} | ${c.failCode ?? '—'} | ${(c.note ?? '').replace(/\|/g, '\\|')} |`,
    );
  }
  if (criticals.length > shown.length) {
    rows.push('');
    rows.push(`_…and ${criticals.length - shown.length} more critical failures._`);
  }
  return rows.join('\n') + '\n';
}

export function renderProfileReportMd(
  report: ProfileReport,
  profile: BeneficiaryProfile,
): string {
  const lines: string[] = [];

  lines.push(`# Parity Report — ${profile.id} · ${profile.name}`);
  lines.push('');
  lines.push(
    `**State/County:** ${profile.state} · ${profile.countyName} (FIPS ${profile.countyFips}) · ZIP ${profile.zip}`,
  );
  lines.push(`**Run at:** ${report.runAt}`);
  lines.push(`**Audit focus:** ${profile.auditFocus}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  const totalCritical = report.planComparisons.reduce(
    (sum, pc) => sum + countCritical(pc.comparisons),
    0,
  );
  lines.push(`- Plans compared: **${report.planComparisons.length}**`);
  lines.push(
    `- Aggregate unweighted pass rate: **${fmtPct(report.aggregatePassRate)}**`,
  );
  lines.push(
    `- Aggregate weighted rate: **${fmtPct(report.aggregateWeightedRate)}**`,
  );
  lines.push(`- Total critical failures: **${totalCritical}**`);
  lines.push('');

  lines.push('## Per-Plan Detail');
  lines.push('');
  for (const pc of report.planComparisons) {
    lines.push(planSection(pc));
  }

  lines.push('## Critical Failures (top 20)');
  lines.push('');
  lines.push(criticalTable(report.criticalFailures));
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(
    `_Generated by \`scripts/parity-audit\` on ${report.runAt} for profile ${profile.id}._`,
  );
  lines.push('');

  return lines.join('\n');
}
